---@class hs.eventtap.event.touch
---@field device string
---@field deviceSize { w: number, h: number }
---@field force number
---@field identity string
---@field phase Phases
---@field resting boolean
---@field timestamp number
---@field touching number
---@field type 'direct' | 'indirect'
---@field normalizedPosition? Position
---@field previousNormalizedPosition? Position